### ISSUE TITLE
Home Assistant errors even though integration seems to function correctly

### ISSUE THREAD

**Issue by HumanSkunk** [bmccluskey/robovac#2]
I have 2 Robovacs added through the integration. A 15C and 15C Max. Both seem to function and are controllable though both the front end and automations. However I am getting persistent error messages in the logs despite functionality seemingly being fine. The errors are repeated every few hours for both vacuums and they usually appear rapidly one after another.

Home Assistant 2022.10.4
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest
HACS 1.28.0

I have obfuscated the IDs and the IPs for the Vacuums, but the messages are exactly the same for both.
 
```
This error originated from a custom integration.

Logger: custom_components.robovac.tuyalocalapi
Source: custom_components/robovac/tuyalocalapi.py:741 
Integration: Eufy Robovac 
First occurred: 23:15:29 (16 occurrences) 
Last logged: 23:26:56

Connection to xxxxxxxxxxxxxxxxxxxxxxxxx (192.168.0.XXX:6668) failed: [Errno 104] Connection reset by peer
```

**Comment by HumanSkunk** [comment]
Just an update but the number of messages seem to increase periodically and then it goes quiet again for a while. My guess some issue with polling where the device is responding with an error. Is there any where to turn this off?
![64BECE07-308E-43BC-9D30-31C7B58FA1DC](https://user-images.githubusercontent.com/62327733/197177995-0047d0c6-e333-47bf-a02a-31e08e07ddf0.jpeg)

**Comment by bmccluskey** [comment]
I was seening these sorts of messages when I was doing testing and had connections from 2 HA.  Are you also connected with the eufy phone app?  
I think the problm is the network card in the 15C can only handle one connection at a time and if it overlaps then it refuses the second connection. 
You could try decreasing the polling interval and that will reduce the frequency.  line 89 in in vacuum.py
REFRESH_RATE = 20
Try changing to 60.

**Comment by HumanSkunk** [comment]
Yea I have the app loaded and I only use it to get the vacuum unstuck, I am trying to get that resolved with a script. I will try closing the Eufy app on the phone or does it need to actually be deleted?

**Comment by bmccluskey** [comment]
Just closed should be enough. The 15c doesnt seem to like to talking to more than one thing at a time.

**Comment by HumanSkunk** [comment]
> Just closed should be enough. The 15c doesnt seem to like to talking to more than one thing at a time.

Having closed the app I haven’t seen a message in over 90 mins. If this is the case and I don’t see any more for the next few hours then my issue has been solved. Will report back if anything changes. Thanks

**Comment by HumanSkunk** [comment]
Ok still getting the error. I will edit the number in the config and see if that changes anything. If anything is there any way to just to get it to ignore the error? I guess that isnt really fixing the issue, but if the issue is hardware based then perhaps just blocking the message within HA is an option?

**Comment by bmccluskey** [comment]
If you really want to hide it the edit tuyalocalapi.py line 741 and change  _LOGGER.error to  _LOGGER.info should do the trick.

**Comment by HumanSkunk** [comment]
Increasing the timeout has massively reduced the amount of errors to only a few per day, so content this can be closed.
