### ISSUE TITLE
Add RoboVacs with existing Access Token / without the necessity of access to the internet for the integreation 

### ISSUE THREAD

**Issue by mirko** [bmccluskey/robovac#9]
Hello,

I'm trying to keep my IoT devices as locally controlled / away from the internet as possible.
As a matter of fact, even home-assistant itself doesn't have access to the internet in my very case.
For my RoboVacs I already do have the necessary access tokens.
I'd really appreciate a short guide - even if it's hacked up - on how to add RoboVacs via this integration by IP address / hostname and access token rather than Eufy credentials which will then used to interact with the Eufy cloud.

Thanks for your work!

**Comment by bmccluskey** [comment]
The communication with eufy is only done once to get the keys and other details on the robot when you very first set up the integration.  After that all communication is local and eufy is not contacted again (Unless you reset up the integration).  The manual steps to configure and set it up would be complex and take me quite a while to even begin to figure out.
